### ISSUE TITLE
[Feature Request] Respawn on zone pass

### ISSUE THREAD

**Issue by mavproductions** [oscar-wos/Retakes-Zones#1]
Hey rasco!

Wondering how easy it would be to implement another style of zones to incorporate with the current style available. (love it btw)😉

The idea I have is that they say `css_zonestyle 0/1/2`

0 = off
1 = current style (just nudge them)
2 = teleport them back to their original spawn point.

I understand for retakes this style this is merely game-breaking, but it would be amazing if this plugin could hybrid as an anti-rush/spawn protection/zone management system.

I know that's a lot, I'm use to rejection, so no worries if it's not a priority. Thanks again for this plugin!

-maV.

**Comment by oscar-wos** [comment]
https://github.com/oscar-wos/AntiRush
